# Generated by Django 4.1.7 on 2023-03-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedapplication',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
